# Site settings
title: Thanh-Linh Nguyen
tag_text: Welcome to my homepage
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

# Blog pagination and post url structure
permalink:     '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
comments: true
